/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.grocerystore;
import java.util.*;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.DecimalFormat;;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author dinie
 */
public class GroceryStoreUI extends javax.swing.JFrame implements Calculation {
    PrintWriter output; //print object into a file,
    Scanner input;
    File datafile = new File("/Users/dinie/NetBeansProjects/Grocery_Store/src/my/grocerystore/DataFile");
    int counter = 0;
    ArrayList<String[]> productDataArray = new ArrayList<String[]>();
    ArrayList<String[]> dataLine = new ArrayList<String[]>();
    String[] productData = new String[5];
    /*
     * Creates new form GroceryStoreUI
     */
    public GroceryStoreUI() {
        initComponents();
        try 
            {
                input = new Scanner (datafile);
                while (input.hasNextLine()) // 4... 
                {   dataLine.add(input.nextLine().split(","));
                }   
            } 
            catch (FileNotFoundException ex) {
                Logger.getLogger(GroceryStoreUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            productDataArray = dataLine;
            System.out.println(Arrays.deepToString(productDataArray.toArray())); // 6... 
    }
    
    @Override
    public double totalPrice(){
        int quantity = Integer.parseInt(quantityJTF.getText());
        double price = Double.parseDouble(pricePerUnitJTF.getText());
        double totalPrice=quantity*price;
        return totalPrice;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groceryStoreJTP = new javax.swing.JTabbedPane();
        addProductJP = new javax.swing.JPanel();
        itemBatchNoJL = new javax.swing.JLabel();
        categoryJL = new javax.swing.JLabel();
        itemNameJL = new javax.swing.JLabel();
        quantityJL = new javax.swing.JLabel();
        pricePerUnitJL = new javax.swing.JLabel();
        totalPriceJL = new javax.swing.JLabel();
        itemBatchNoJTF = new javax.swing.JTextField();
        categoryJCB = new javax.swing.JComboBox<>();
        itemNameJTF = new javax.swing.JTextField();
        quantityJTF = new javax.swing.JTextField();
        pricePerUnitJTF = new javax.swing.JTextField();
        saveJB = new javax.swing.JButton();
        clearJB = new javax.swing.JButton();
        totalPriceJTF = new javax.swing.JTextField();
        calculateJB = new javax.swing.JButton();
        dateJTF = new javax.swing.JTextField();
        showDateJB = new javax.swing.JButton();
        hideDateJB = new javax.swing.JButton();
        inventoryJP = new javax.swing.JPanel();
        scrollerJSP = new javax.swing.JScrollPane();
        inventoryJTA = new javax.swing.JTextArea();
        deleteJB = new javax.swing.JButton();
        groceryStoreJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));

        groceryStoreJTP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        groceryStoreJTP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                groceryStoreJTPStateChanged(evt);
            }
        });
        groceryStoreJTP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                groceryStoreJTPFocusGained(evt);
            }
        });

        itemBatchNoJL.setText("Item Batch No :");

        categoryJL.setText("Category :");

        itemNameJL.setText("Item Name : ");

        quantityJL.setText("Quantity ;");

        pricePerUnitJL.setText("Price per Unit :");

        totalPriceJL.setText("Total Price :");

        itemBatchNoJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBatchNoJTFActionPerformed(evt);
            }
        });

        categoryJCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-     ", "Produce", "Dairy", "Meat" }));
        categoryJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryJCBActionPerformed(evt);
            }
        });

        itemNameJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameJTFActionPerformed(evt);
            }
        });

        saveJB.setText("Save");
        saveJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJBActionPerformed(evt);
            }
        });

        clearJB.setText("Clear");
        clearJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJBActionPerformed(evt);
            }
        });

        totalPriceJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceJTFActionPerformed(evt);
            }
        });

        calculateJB.setText("Calculate");
        calculateJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJBActionPerformed(evt);
            }
        });

        showDateJB.setText("Show date");
        showDateJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDateJBActionPerformed(evt);
            }
        });

        hideDateJB.setText("Hide date");
        hideDateJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideDateJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addProductJPLayout = new javax.swing.GroupLayout(addProductJP);
        addProductJP.setLayout(addProductJPLayout);
        addProductJPLayout.setHorizontalGroup(
            addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductJPLayout.createSequentialGroup()
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProductJPLayout.createSequentialGroup()
                        .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductJPLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(categoryJL)
                                    .addComponent(itemBatchNoJL)
                                    .addComponent(itemNameJL)
                                    .addComponent(quantityJL)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductJPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pricePerUnitJL, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalPriceJL, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(33, 33, 33)
                        .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityJTF)
                            .addComponent(pricePerUnitJTF)
                            .addComponent(categoryJCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemNameJTF)
                            .addComponent(itemBatchNoJTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalPriceJTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductJPLayout.createSequentialGroup()
                        .addGap(0, 213, Short.MAX_VALUE)
                        .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductJPLayout.createSequentialGroup()
                                .addComponent(hideDateJB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showDateJB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductJPLayout.createSequentialGroup()
                                .addComponent(calculateJB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveJB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearJB)))))
                .addContainerGap())
        );
        addProductJPLayout.setVerticalGroup(
            addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDateJB)
                    .addComponent(hideDateJB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemBatchNoJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemBatchNoJL))
                .addGap(18, 18, 18)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryJL))
                .addGap(18, 18, 18)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameJL))
                .addGap(18, 18, 18)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityJL))
                .addGap(18, 18, 18)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricePerUnitJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricePerUnitJL))
                .addGap(18, 18, 18)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPriceJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPriceJL))
                .addGap(27, 27, 27)
                .addGroup(addProductJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateJB)
                    .addComponent(saveJB)
                    .addComponent(clearJB))
                .addGap(62, 62, 62))
        );

        groceryStoreJTP.addTab("Add Product", addProductJP);

        inventoryJTA.setColumns(20);
        inventoryJTA.setRows(5);
        scrollerJSP.setViewportView(inventoryJTA);

        deleteJB.setText("Delete");
        deleteJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventoryJPLayout = new javax.swing.GroupLayout(inventoryJP);
        inventoryJP.setLayout(inventoryJPLayout);
        inventoryJPLayout.setHorizontalGroup(
            inventoryJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollerJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryJPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteJB)
                .addGap(35, 35, 35))
        );
        inventoryJPLayout.setVerticalGroup(
            inventoryJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollerJSP, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteJB)
                .addGap(5, 5, 5))
        );

        groceryStoreJTP.addTab("View Inventory", inventoryJP);

        groceryStoreJL.setBackground(new java.awt.Color(255, 153, 153));
        groceryStoreJL.setFont(new java.awt.Font("Luminari", 1, 48)); // NOI18N
        groceryStoreJL.setText("Grocery Store");
        groceryStoreJL.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(groceryStoreJL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(groceryStoreJTP, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(groceryStoreJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groceryStoreJTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBatchNoJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBatchNoJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBatchNoJTFActionPerformed

    private void itemNameJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameJTFActionPerformed

    private void saveJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJBActionPerformed
        String batchNo = itemBatchNoJTF.getText();
        String category = String.valueOf(categoryJCB.getSelectedItem()); 
        String itemName = itemNameJTF.getText();

        /*productData[0] = batchNo;
        productData[1] = category;
        productData[2] = itemName;
        productData[3] = quantityJTF.getText();
        productData[4] = priceJTF.getText();*/
        
        String[] productData = {batchNo, category, itemName, quantityJTF.getText(),pricePerUnitJTF.getText()};
        productDataArray.add(productData);
        System.out.println(Arrays.deepToString(productDataArray.toArray()));

        try {
            output = new PrintWriter(datafile); // 8...
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GroceryStoreUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String[] i : productDataArray)
        {   for (int j = 0; j < 5; j++)
        {   System.out.print(i[j]+",");
            output.print(i[j]+",");//print into datafile
        }
            System.out.println();
            output.println();
        }
    output.close();
    }//GEN-LAST:event_saveJBActionPerformed

    private void groceryStoreJTPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_groceryStoreJTPStateChanged
        counter++;
        System.out.println(counter);//references
        if (counter % 2 == 0) {
            try {
                input = new Scanner(datafile);
                dataLine = new ArrayList<String[]>();
                while (input.hasNextLine())
                {   dataLine.add(input.nextLine().split(","));// 
                }    
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GroceryStoreUI.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
            productDataArray = dataLine;
            inventoryJTA.setText("");//clear out the text area so it doesn't add up
            for (String[] i : productDataArray)
            {   String dataOutput = "Batch No :"+i[0]+"\tCategory : "+i[1]+"\tItem Name : "+i[2]+"\tQuantity : "+i[3]+ "\tPrice : "+i[4];
                System.out.println(dataOutput);
                inventoryJTA.append(dataOutput+"\n");//12...++
            }
        }
    }//GEN-LAST:event_groceryStoreJTPStateChanged

    private void groceryStoreJTPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_groceryStoreJTPFocusGained
        // TODO add your handling code here: 
    }//GEN-LAST:event_groceryStoreJTPFocusGained

    private void categoryJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryJCBActionPerformed

    private void clearJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJBActionPerformed
        itemBatchNoJTF.setText("");
        itemNameJTF.setText("");
        quantityJTF.setText("");
        pricePerUnitJTF.setText("");
        totalPriceJTF.setText("");
        categoryJCB.setSelectedItem("-     ");
    }//GEN-LAST:event_clearJBActionPerformed

    private void deleteJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJBActionPerformed
        inventoryJTA.setText("");
        PrintWriter clearedOutput = null;
        try{
            clearedOutput = new PrintWriter(datafile);
        } catch (FileNotFoundException e){
            e.printStackTrace(); // 11... what is this?
        }
    }//GEN-LAST:event_deleteJBActionPerformed

    private void totalPriceJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceJTFActionPerformed
        
    }//GEN-LAST:event_totalPriceJTFActionPerformed

    private void calculateJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJBActionPerformed
        System.out.println(totalPrice());
        totalPriceJTF.setText(String.valueOf(totalPrice()));    
    }//GEN-LAST:event_calculateJBActionPerformed

    private void hideDateJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideDateJBActionPerformed
        dateJTF.setText("");
    }//GEN-LAST:event_hideDateJBActionPerformed

    private void showDateJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDateJBActionPerformed
        Date date = new Date(15,9,2021);
        dateJTF.setText(date.displayDate());
    }//GEN-LAST:event_showDateJBActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.*/

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroceryStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GroceryStoreUI().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addProductJP;
    private javax.swing.JButton calculateJB;
    public javax.swing.JComboBox<String> categoryJCB;
    private javax.swing.JLabel categoryJL;
    private javax.swing.JButton clearJB;
    private javax.swing.JTextField dateJTF;
    private javax.swing.JButton deleteJB;
    private javax.swing.JLabel groceryStoreJL;
    private javax.swing.JTabbedPane groceryStoreJTP;
    private javax.swing.JButton hideDateJB;
    private javax.swing.JPanel inventoryJP;
    private javax.swing.JTextArea inventoryJTA;
    private javax.swing.JLabel itemBatchNoJL;
    private javax.swing.JTextField itemBatchNoJTF;
    private javax.swing.JLabel itemNameJL;
    private javax.swing.JTextField itemNameJTF;
    private javax.swing.JLabel pricePerUnitJL;
    private javax.swing.JTextField pricePerUnitJTF;
    private javax.swing.JLabel quantityJL;
    private javax.swing.JTextField quantityJTF;
    private javax.swing.JButton saveJB;
    private javax.swing.JScrollPane scrollerJSP;
    private javax.swing.JButton showDateJB;
    private javax.swing.JLabel totalPriceJL;
    private javax.swing.JTextField totalPriceJTF;
    // End of variables declaration//GEN-END:variables
}//end class